Fix environment variable parsing for String types
Previously would result in error if for instance one did for instance

CLIMATEMACHINE_SETTINGS_VTK="100steps" julia -J.git/ClimateMachine.sys --project test/Atmos/Model/discrete-hydrostatic-balance.jl

since `tryparse(String, "100steps")`

```
ERROR: MethodError: no method matching tryparse(::Type{String}, ::String)
Closest candidates are:
  tryparse(::Type{T}, ::AbstractString; base) where T<:Integer at parse.jl:234
  tryparse(::Type{Float64}, ::String) at parse.jl:245
  tryparse(::Type{Float32}, ::String) at parse.jl:265
  ...
Stacktrace:
 [1] top-level scope at REPL[2]:1
```